import { hoursLabel, reportSnapshotSchema, type ReportSnapshot } from "./index.js";

const coverageLabels = { available: "可用", "no-data": "无数据（不代表零工时）", unknown: "未知（不主张工时）" };
const sourceLabels = { fixture: "测试数据", history: "Codex", "claude-history": "Claude Code", "cursor-history": "Cursor", hook: "Codex Hook", git: "Git 提交" };
const evidenceLabels = { "explicit-ticket": "明确票据", "planning-reference": "规划文档", branch: "分支", "merge-subject": "合并提交主题", "commit-subject": "提交主题", path: "改动路径", semantic: "语义推断" };
const confidenceLabels = { high: "高", medium: "中", low: "低" };
const warningLabels = { "invalid-timestamp": "无效时间戳", "missing-turn-stop": "回合缺少结束边界", "missing-tool-post": "工具缺少结束边界", "unmatched-tool-post": "工具结束没有匹配开始", "out-of-order-tool-event": "工具事件顺序异常", "negative-tool-interval": "工具区间为负", "out-of-order-turn-event": "回合事件顺序异常" };
const escape = (value: string) => value.replace(/[&<>"']/gu, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const metric = (value: number | null) => value === null ? "—（无法确认）" : hoursLabel(value);
const money = (cents: number) => `¥${new Intl.NumberFormat("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(cents / 100)}`;
const table = (headers: string[], rows: string[], className = "detail-table") => `<div class="table-scroll" tabindex="0" role="region" aria-label="${escape(headers.join("、"))}"><table class="${className}"><thead><tr>${headers.map((header) => `<th>${escape(header)}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`;
const cells = (values: string[]) => `<tr>${values.map((value) => `<td>${value}</td>`).join("")}</tr>`;

/** Pure, offline rendering of the saved privacy whitelist; no Node, templates or sources. */
export function renderReportSnapshot(value: ReportSnapshot, view: "internal" | "customer" = "internal"): string {
  const snapshot = reportSnapshotSchema.parse(value);
  const internal = view === "internal";
  const { totals, rate } = snapshot;
  const coverageSummary = { available: 0, "no-data": 0, unknown: 0 };
  for (const day of snapshot.days) coverageSummary[day.coverage]++;
  const eventCount = snapshot.sources.filter((source) => source.source !== "git").reduce((n, source) => n + source.eventCount, 0);
  const overview = internal ? `<section class="estimate-overview" aria-label="提交节奏推测总工时与费用"><div><span class="estimate-label">推测总工时（非核验）</span><strong class="estimate-value">${metric(totals.commitEstimateMs)}</strong><span class="estimate-note">${totals.commitEstimateMs === null ? "—" : (totals.commitEstimateMs / (rate.hoursPerDay * 3_600_000)).toFixed(2)} 人天（${rate.hoursPerDay} 小时 / 人天）</span></div><div><span class="estimate-label">推测费用</span><strong class="estimate-value">${totals.estimatedCostCents === null ? "—（无法确认）" : money(totals.estimatedCostCents)}</strong><span class="estimate-note">按 ${money(rate.dayRateCents)} / 人天估算</span></div><div><span class="estimate-label">估算口径</span><strong class="estimate-value">提交节奏</strong><span class="estimate-note">不是已核验 AI 或人工工时</span></div></section>` : "";
  const dailyRows = snapshot.days.map((day) => {
    const titles = day.commitMessages.map((message) => `<li>${escape(message.title)}${message.count > 1 ? ` × ${message.count}` : ""}</li>`);
    const messages = titles.length ? `<ul>${titles.slice(0, 3).join("")}</ul>${titles.length > 3 ? `<details><summary>展开其余 ${titles.length - 3} 条提交信息</summary><ul>${titles.slice(3).join("")}</ul></details>` : ""}` : "—";
    const commits = day.commitCount ? `<strong>${day.commitCount} 个提交</strong><br><span class="muted">${day.commitGroups.map((group) => `${escape(group.label)} × ${group.commitCount}`).join(" · ")}</span>` : "—";
    const estimate = day.commitEstimateMs === null ? "—" : `<strong>${hoursLabel(day.commitEstimateMs)}</strong><br><span class="muted">${day.commitGroups.filter((group) => group.estimatedMs > 0).map((group) => `${escape(group.label)} × ${hoursLabel(group.estimatedMs)}`).join(" · ")}</span>`;
    return `<tr aria-label="${day.date}: ${coverageLabels[day.coverage]}"><td>${day.date}</td><td class="number">${metric(day.activeMs)}</td>${internal ? `<td>${commits}</td><td class="commit-messages">${messages}</td><td>${estimate}</td>` : ""}<td>${coverageLabels[day.coverage]}</td></tr>`;
  });
  const totalsByFeature = new Map(snapshot.featureIntervalTotals.map((total) => [total.featureId, total]));
  const attributionsByFeature = new Map<string, ReportSnapshot["featureAttributions"]>();
  for (const attribution of snapshot.featureAttributions) {
    const rows = attributionsByFeature.get(attribution.featureId) ?? [];
    rows.push(attribution);
    attributionsByFeature.set(attribution.featureId, rows);
  }
  const featureIds = [...new Set([...attributionsByFeature.keys(), ...(internal ? totalsByFeature.keys() : [])])];
  const featureRows = featureIds.map((featureId) => {
    const attributions = attributionsByFeature.get(featureId) ?? [];
    const total = totalsByFeature.get(featureId);
    const evidence = attributions.length ? attributions.map((attribution) => `${evidenceLabels[attribution.evidence]} · ${confidenceLabels[attribution.confidence]}可信度${attribution.suggested ? "（建议，非确认归因）" : ""}`).join("<br>") : "已明确关联区间 · 高可信度";
    return cells([escape(attributions[0]?.featureName ?? featureId), evidence, total ? metric(total.activeMs) : "未分配", total ? metric(total.runMs) : "未分配", ...(internal ? [total ? String(total.evidenceCount) : "—"] : [])]);
  });
  if (!featureRows.length) featureRows.push(`<tr><td colspan="${internal ? 5 : 4}" class="muted">没有功能归因证据；Git scope 不是 Feature，不主张功能时长。</td></tr>`);
  const sources = internal ? `<tr><td>采集来源</td><td>${snapshot.sources.map((source) => `${sourceLabels[source.source]} ${source.eventCount} 条（${coverageLabels[source.status]}）`).join(" · ")}</td><td>只保存脱敏统计，不保存会话身份、目录或对话正文。未知来源可能不存在或不可读。</td></tr>` : "";
  const cursor = snapshot.cursorUndated;
  const warnings = internal && snapshot.integrity.length ? `<section class="panel"><h2>事件完整性与审计明细</h2><p class="panel-note">事件边界不完整时不合成工时；Coverage 与完整性是独立指标。</p><details><summary>查看数据质量警告</summary><ul>${snapshot.integrity.map((warning) => `<li>${warningLabels[warning.reason]}（${warning.reason}） × ${warning.count}</li>`).join("")}</ul></details></section>` : "";
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(snapshot.project.displayName)} — Codex Worktime</title><style>
:root{color-scheme:light;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#162033;background:#edf2f9}*{box-sizing:border-box}body{margin:0;padding:2rem 1rem 4rem;background:radial-gradient(circle at top right,#dbeafe,transparent 32rem),#edf2f9}main{margin:0 auto;max-width:72rem}.hero{padding:2.5rem;border-radius:1.5rem;background:linear-gradient(135deg,#102a43,#1e4976);color:#f8fbff;box-shadow:0 1.5rem 3rem rgba(22,32,51,.18)}.eyebrow{color:#b9d5f3;font-size:.78rem;font-weight:750}h1{margin:0;font-size:clamp(2rem,5vw,3.4rem);letter-spacing:-.04em}h2{margin:0 0 1rem;font-size:1.15rem}h3{font-size:.9rem;color:#4a5b72}.hero-copy,.report-range{color:#d8eafa}.status{display:inline-flex;padding:.42rem .72rem;border-radius:999px;background:rgba(255,255,255,.13);font-size:.85rem}.estimate-overview{display:grid;grid-template-columns:1.35fr repeat(2,1fr);gap:1px;margin:1.25rem 0;overflow:hidden;border:1px solid #c6d9ee;border-radius:1rem;background:#c6d9ee}.estimate-overview>div{padding:1.2rem 1.3rem;background:#f8fbff}.estimate-overview>div:first-child{background:#e7f1ff}.estimate-label,.metric-label{display:block;color:#28557f;font-size:.76rem;font-weight:800}.estimate-value,.metric-value{display:block;margin-top:.45rem;color:#102a43;font-size:clamp(1.35rem,3vw,2rem);font-weight:850}.estimate-note,.metric-note{display:block;margin-top:.35rem;color:#60708a;font-size:.84rem;line-height:1.45}.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin:1.25rem 0}.metric{padding:1.25rem;border:1px solid #dce6f2;border-radius:1rem;background:#fff}.panel{margin-top:1.25rem;padding:1.4rem;border:1px solid #dce6f2;border-radius:1rem;background:rgba(255,255,255,.96);box-shadow:0 .5rem 1.5rem rgba(31,62,93,.05)}.panel-note{color:#60708a;font-size:.9rem;line-height:1.5}.table-scroll{overflow-x:auto}table{width:100%;border-collapse:collapse;border:1px solid #e3ebf5}th,td{padding:.78rem .85rem;border-bottom:1px solid #e7eef7;text-align:left;vertical-align:top;font-size:.88rem}th{color:#51637c;background:#f6f9fd;font-size:.72rem;font-weight:800}.daily-table{min-width:66rem}.number{font-variant-numeric:tabular-nums;font-weight:750}.muted{color:#60708a}.commit-messages{min-width:16rem;max-width:24rem;overflow-wrap:anywhere}.commit-messages ul{margin:0;padding-left:1.1rem}.commit-messages li+li{margin-top:.4rem}details{margin-top:.6rem}details ul{margin-top:.6rem}summary{cursor:pointer;color:#28557f;font-weight:750}:focus-visible{outline:3px solid #2563eb;outline-offset:3px}@media(max-width:40rem){body{padding:1rem .75rem 2rem}.hero,.panel{padding:1.15rem}.estimate-overview,.metric-grid{grid-template-columns:1fr}th,td{padding:.65rem}}
</style></head><body><main><header class="hero"><p class="eyebrow">Codex Worktime · ${internal ? "内部报告" : "客户报告"}</p><h1>${escape(snapshot.project.displayName)}</h1><p class="hero-copy">${internal ? `${eventCount} 条脱敏事件匹配此 Project Profile。` : "客户视图仅包含已批准的汇总报告字段。"}</p><p class="status">${eventCount || totals.activeMs !== null || totals.runMs !== null ? "数据可用" : "无可确认数据"}</p><p class="report-range">${snapshot.period.from} 至 ${snapshot.period.to} (Asia/Shanghai)</p></header>${overview}
<section class="metric-grid" aria-label="已核验指标"><article class="metric"><span class="metric-label">活跃区间</span><strong class="metric-value">${metric(totals.activeMs)}</strong><p class="metric-note">已核验的墙钟时间并集${internal ? `；${metric(totals.parallelActiveMs)}并行机器时间` : ""}。</p></article><article class="metric"><span class="metric-label">运行区间</span><strong class="metric-value">${metric(totals.runMs)}</strong><p class="metric-note">仅统计可观察的工具执行或等待。</p></article><article class="metric"><span class="metric-label">数据覆盖</span><strong class="metric-value">${coverageSummary.available} 天可用</strong><p class="metric-note">${coverageSummary.unknown} 天未知 · ${coverageSummary["no-data"]} 天无数据；两者都不代表零工时。</p></article></section>
<section class="panel"><h2>已核验数据 · 汇总</h2><p class="panel-note">活跃区间与运行区间是两个独立、由事件边界确定的指标；本报告不包含推算的人类工时。</p>${table(["指标", "已核验值", "说明"], [cells(["活跃区间", metric(totals.activeMs), "由完整的 UserPromptSubmit → Stop 区间构成。"]), cells(["运行区间", metric(totals.runMs), "由完整的 PreToolUse → PostToolUse 区间构成。"]), sources, cells(["数据覆盖", `${coverageSummary.available} 天可用 / ${coverageSummary.unknown} 天未知 / ${coverageSummary["no-data"]} 天无数据`, "未知或无数据都不代表零工时。"])], "summary-table")}${internal ? `<p class="panel-note">Cursor 无法定月累计：${cursor.sessionCount} 个会话 · ${cursor.promptCount} 次提问 · ${cursor.completedTurnCount} 个完成回合 · ${cursor.missingTimestampCount} 条无时间戳记录；不是本月数量，不据此主张月内工时。</p>` : ""}</section>
<section class="panel"><h2>${internal ? "已核验区间、提交节奏与数据覆盖" : "已核验区间与数据覆盖"}</h2><h3>${internal ? "按日活跃、提交与覆盖情况" : "按日活跃与覆盖情况"}（Asia/Shanghai）</h3>${internal ? `<p class="panel-note">提交节奏推测只累计相邻且同一 scope 的提交间隔，每段最多 1 小时；它不是已核验 AI 或人工工时。</p>` : ""}${table(["日期", "已核验活跃", ...(internal ? ["提交历史汇总", "当天 Commit Message", "提交节奏推测（非核验）"] : []), "无数据与覆盖情况"], dailyRows, "detail-table daily-table")}<h3>按周 AI 活动（Asia/Shanghai）</h3>${table(["周", "已核验活跃（小时）", "已核验运行（小时）"], snapshot.weekly.map((week) => cells([week.week, metric(week.activeMs), metric(week.runMs)])))}</section>
<section class="panel"><h2>推断的交付证据 · 功能归因与已核验小时</h2><p class="panel-note">Git 只提供交付证据。功能只有在审阅证据将其关联到已核验区间时才会获得时长；commit 时间戳不会产生已核验工时。Git scope 不是真正的 Feature。</p>${table(["功能", "证据 / 可信度", "已核验活跃", "已核验运行", ...(internal ? ["证据数量"] : [])], featureRows)}${snapshot.featureTotalsUnavailableForRange ? `<p class="panel-note">未提供该报告范围内的功能区间关联证据，因此不主张功能时长。</p>` : ""}</section>${warnings}<footer class="panel-note">Schema ${snapshot.schemaVersion} · ${snapshot.algorithmVersion} · 生成于 ${escape(snapshot.generatedAt)}</footer></main></body></html>`;
}
